# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
maven_group=com.github.stellarwind23
# REMEMBER: update in common init!
modid=template
archives_name=Template
mod_version=1.0.0-beta
author=StellarWind23
enabled_platforms=fabric,neoforge
homepage_url=
issues_url=
license=MIT
description=TODO: Change template description.
# Minecraft properties
minecraft_version=1.21.11
java_version=21
# Dependencies
architectury_api_version=19.0.1
fabric_loader_version=0.19.2
fabric_api_version=0.141.4+1.21.11
neoforge_version=21.11.42
